### PR TITLE
po: rewrite some strings and mark as translatable

### PR DESCRIPTION
**Pull request by oscfdezdz**
Following common GTK/GNOME applications patterns.

### CODE REVIEW

**Comment by oscfdezdz** [comment]
> NameError: name '_' is not defined

Translations are working as they should though.

**Comment by lachhebo** [comment]
may be we should remove the broken test (comment it for example) until we find a solution to make it work

**Comment by lachhebo** [comment]
[here](https://docs.python.org/fr/3/library/gettext.html) is what i found when i looked at the subject on internet

```python
import gettext
gettext.bindtextdomain('myapplication', '/path/to/my/language/directory')
gettext.textdomain('myapplication')
_ = gettext.gettext
# ...
print(_('This is a translatable string.'))
```

**Comment by oscfdezdz** [comment]
I thought that was taken care of in `gabtag.in` since translations work 🤔

**Review by lachhebo — APPROVED** [review]

**Pull request merged**
