### PR TITLE
port to libhandy

### PR DESCRIPTION
**Pull request by oscfdezdz**
There are still a few papercuts I'd like to tackle. As of now, it's not following HIG as much as I'd like it to, but I'll leave those for future PRs.

I didn't experience any regressions but there could be of course :)

imagen
imagen
imagen

### CODE REVIEW

**Comment by lachhebo** [comment]
The library i used before to find the lyrics was deprecated so this feature is not anymore available in gabtag, i think we should also find another library or remove the lyrics box in future PR

**Review by lachhebo — APPROVED** [review]

**Comment by oscfdezdz** [comment]
I can remove that from the UI now if you want.

Also, I made some changes a few minutes back to covers, hopefully it's not to late to add them here.

imagen
imagen

**Comment by lachhebo** [comment]
Yes it would be great, I think you can also merge now (you can click on merge pr if you want) I let you choose

**Comment by oscfdezdz** [comment]
Lyrics feature is now gone from UI. It seems like I can't merge.

**Pull request merged**
